# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "8a99a96415dae17b37472a7ab68b6978a7255bdb4430cd84a3288a70d4b392a5"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3cc92220ad1f363556e51f40e8270f5e213acba38720b15a23a1b9631501536e"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "582519306719e19bb386c3cae06c97c3aaef74372f156e936930b07567592d2a"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4538b9bda0517ea18b1f160f101c22ba0309c75b79ef89a66565ec10f7ad9fac"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
    end
  end

  name "courier"
  desc "Safely transfer files and directories between local and SSH endpoints."
  homepage "https://github.com/iwonz/courier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  # No zap stanza required
end
