# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f53a75bcf39f83701c53df4c5f2cefb7d0017c80bab4fd5f9e329f1a50ec4239"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d443cb0c96e753ea116eb3b496fb93fd9d57d03b7009ae10dde5622106e8684"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc25137fc0c3273c3c374af22e4e037b4c1b8132b6348496be9dc86a5de2f0a8"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c97da5d1eaa3ce07f8b1b4e6cd54d721fe0a218577951b839d9b24e9961b42b9"
      url "https://github.com/iwonz/courier/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
    end
  end

  name "courier"
  desc "Safely transfer files and directories between local and SSH endpoints."
  homepage "https://github.com/iwonz/courier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  # No zap stanza required
end
