import { parseLocale, type Locale } from "@courier/ui";

const en = {
  brandProduct: "File delivery CLI",
  eyebrow: "Open source · MIT · self-contained",
  title: "Move files. Keep control.",
  tagline: "A dependable CLI for local, SSH, browser, and webhook deliveries.",
  subline: "One binary plans the route, protects the destination, and reports only the bytes it can confirm.",
  install: "Install Courier",
  installShort: "Install",
  commands: "Command map",
  routes: "Route map",
  options: "Option registry",
  examples: "Field examples",
  downloads: "Release downloads",
  documentation: "Documentation",
  source: "Source on GitHub",
  releases: "GitHub Releases",
  installIntro: "Choose a repository-owned channel. Every release resolves to the same dependency-free Courier binary.",
  primaryChannel: "Recommended · macOS and Linux",
  alternateChannels: "Other dispatch channels",
  packages: "Native Linux packages",
  packagesDetail: "Deb, RPM, APK, and Arch packages cover Ubuntu, Debian, Fedora, RHEL, Alpine, Arch Linux, and Manjaro.",
  direct: "Direct binaries",
  directDetail: "Release archives and SHA-256 checksums cover macOS, Linux, Windows, and the supported BSD helpers.",
  commandKind: "Kind",
  commandSyntax: "Command",
  product: "Product",
  system: "System",
  route: "Route",
  from: "Source",
  to: "Destination",
  allowed: "Allowed options",
  option: "Option",
  default: "Default",
  applies: "Applies to",
  repeatable: "Repeatable",
  yes: "yes",
  no: "no",
  version: "Contract",
  target: "Target release",
  security: "Security model",
  cliReference: "CLI reference",
  installGuide: "Installation guide",
  license: "MIT License",
  heroStatus: "Route systems ready",
  heroRouteLabel: "Typical dispatch",
  routeIntro: "Start and end points stay explicit. Courier selects the implementation only after the combination passes preflight.",
  safety: "Built for a safe handoff",
  safetyIntro: "Courier checks before it changes, stages before it commits, and separates sent bytes from confirmed arrival.",
  preflightTitle: "Preflight first",
  preflightDetail: "Identity, collisions, route policy, path safety, and remote trust are checked before destination data changes.",
  stagedTitle: "Staged commit",
  stagedDetail: "Writes use private partial paths and commit into an absent final target where the platform permits it.",
  trustTitle: "SSH trust stays on",
  trustDetail: "Native SSH honors config, known hosts, identities, agents, and ProxyJump without disabling host-key verification.",
  reportTitle: "Verified reporting",
  reportDetail: "Progress separates read, sent, and confirmed bytes, so completion means more than a stream closing.",
  oneBinary: "required runtimes",
  routeFamilies: "route families",
  targetSystems: "client targets",
  inspectContract: "Inspect the full shipped contract",
  finalTitle: "Plan the route. Dispatch once.",
  finalDetail: "Courier remains scriptable in the terminal and understandable at every handoff.",
  footerLine: "Dependable file delivery from source to verified arrival.",
} as const;

type Catalog = { readonly [Key in keyof typeof en]: string };

const ru = {
  brandProduct: "CLI доставки файлов",
  eyebrow: "Открытый код · MIT · автономная работа",
  title: "Переносите файлы. Сохраняйте контроль.",
  tagline: "Надёжный CLI для локальных, SSH, браузерных и webhook-доставок.",
  subline: "Один бинарник планирует маршрут, защищает назначение и сообщает только тот объём, который смог подтвердить.",
  install: "Установить Courier",
  installShort: "Установка",
  commands: "Карта команд",
  routes: "Карта маршрутов",
  options: "Реестр параметров",
  examples: "Рабочие примеры",
  downloads: "Скачать релиз",
  documentation: "Документация",
  source: "Исходный код на GitHub",
  releases: "Релизы GitHub",
  installIntro: "Выберите канал из репозитория. Каждый релиз устанавливает один и тот же автономный бинарник Courier.",
  primaryChannel: "Рекомендуется · macOS и Linux",
  alternateChannels: "Другие каналы доставки",
  packages: "Нативные пакеты Linux",
  packagesDetail: "Пакеты Deb, RPM, APK и Arch поддерживают Ubuntu, Debian, Fedora, RHEL, Alpine, Arch Linux и Manjaro.",
  direct: "Готовые бинарники",
  directDetail: "Архивы релизов и SHA-256 доступны для macOS, Linux, Windows и поддерживаемых BSD helper-сборок.",
  commandKind: "Тип",
  commandSyntax: "Команда",
  product: "Основная",
  system: "Системная",
  route: "Маршрут",
  from: "Источник",
  to: "Назначение",
  allowed: "Допустимые параметры",
  option: "Параметр",
  default: "По умолчанию",
  applies: "Применяется к",
  repeatable: "Повторяемый",
  yes: "да",
  no: "нет",
  version: "Контракт",
  target: "Целевой релиз",
  security: "Модель безопасности",
  cliReference: "Справочник CLI",
  installGuide: "Руководство по установке",
  license: "Лицензия MIT",
  heroStatus: "Маршруты готовы",
  heroRouteLabel: "Типовая доставка",
  routeIntro: "Начальная и конечная точки остаются явными. Courier выбирает реализацию только после успешной предварительной проверки.",
  safety: "Безопасная передача по замыслу",
  safetyIntro: "Courier проверяет до изменений, использует staging до фиксации и отделяет отправленные байты от подтверждённой доставки.",
  preflightTitle: "Сначала проверка",
  preflightDetail: "Совпадения, конфликты, правила маршрута, безопасность пути и доверие SSH проверяются до изменения назначения.",
  stagedTitle: "Фиксация через staging",
  stagedDetail: "Запись идёт во временный приватный путь и фиксируется в отсутствующую конечную цель, где это допускает платформа.",
  trustTitle: "Проверка SSH включена",
  trustDetail: "Нативный SSH учитывает config, known hosts, ключи, agent и ProxyJump без отключения проверки ключа сервера.",
  reportTitle: "Проверяемый отчёт",
  reportDetail: "Прогресс разделяет прочитанные, отправленные и подтверждённые байты — завершение означает больше, чем закрытие потока.",
  oneBinary: "обязательных runtime",
  routeFamilies: "семейства маршрутов",
  targetSystems: "целевых систем",
  inspectContract: "Открыть полный контракт команд",
  finalTitle: "Спланируйте маршрут. Отправьте один раз.",
  finalDetail: "Courier остаётся удобным для скриптов в терминале и понятным на каждом этапе передачи.",
  footerLine: "Надёжная доставка файлов от источника до подтверждённого прибытия.",
} as const satisfies Catalog;

export const landingCatalogs = { en, ru } as const;
export type LandingMessage = keyof typeof en;

export function landingLocale(languages: readonly string[] = globalThis.navigator.languages): Locale {
  for (const language of languages) {
    const locale = parseLocale(language);
    if (locale) return locale;
  }
  return "en";
}

export function landingText(locale: Locale, message: LandingMessage): string {
  return landingCatalogs[locale][message];
}
