import { parseLocale, type Locale } from "@courier/ui";

const en = {
  brandProduct: "File delivery CLI",
  title: "Move files. Keep control.",
  tagline: "A dependable CLI for local, SSH, browser, and webhook deliveries.",
  install: "Install Courier",
  installShort: "Install",
  chooseChannel: "Choose an installation channel",
  copyCommand: "Copy command",
  copiedCommand: "Copied",
  copyFailed: "Copy failed",
  packages: "Linux packages",
  packagesDetail: "Deb, RPM, APK, and Arch packages for Ubuntu, Debian, Fedora, RHEL, Alpine, Arch Linux, and Manjaro.",
  direct: "Direct binaries",
  directDetail: "Signed release archives and checksums for macOS, Linux, Windows, and supported BSD helpers.",
  routeShort: "Routes",
  routeTitle: "Choose the handoff",
  routeIntro: "Choose a Source, then activate a valid Destination.",
  sourceLabel: "Source",
  destinationLabel: "Destination",
  from: "from",
  to: "to",
  allowed: "Available options",
  cliShort: "CLI",
  cliTitle: "Commands and options",
  commandLabel: "Command",
  optionsLabel: "Options",
  compatibleOnly: "Compatible with selected command",
  noCompatibleOptions: "This command has no options.",
  product: "Product",
  system: "System",
  optionDefault: "Default",
  applies: "Applies to",
  repeatable: "Repeatable",
  yes: "yes",
  no: "no",
  githubLabel: "Courier on GitHub",
  runDemo: "Run demo",
  replayDemo: "Replay demo",
  preview: "Browser preview",
  noBrowserEffect: "Preview only. No command, installation, or transfer runs in this browser.",
  routeDemoDescription: "Review the generated command, endpoint meaning, and safe delivery stages.",
  installDemoDescription: "Review how this channel resolves and verifies the Courier release.",
  cliDemoDescription: "Review generated usage and compatible options for the selected command.",
  selectCommand: "Select a command to preview its generated help.",
  demoPreflight: "Preflight",
  demoPreflightDetail: "Validate endpoint syntax and destination safety.",
  demoRoute: "Route",
  demoRouteDetail: "Resolve the selected Source and Destination.",
  demoTransfer: "Transfer",
  demoTransferDetail: "Preview bounded streaming with confirmed-byte accounting.",
  demoVerify: "Verify",
  demoVerifyDetail: "Confirm the received content before reporting success.",
  demoComplete: "Complete",
  demoCompleteDetail: "Preview complete. No data left this page.",
  demoResolve: "Resolve release",
  demoResolveDetail: "Read the latest repository-owned release metadata.",
  demoPlatform: "Select platform",
  demoPlatformDetail: "Match the operating system and architecture.",
  demoDownload: "Download",
  demoDownloadDetail: "Preview retrieval of the matching autonomous artifact.",
  demoChecksum: "Verify checksum",
  demoChecksumDetail: "Compare the artifact with the published checksum.",
  demoInstall: "Install",
  demoInstallDetail: "Preview placement in the channel-managed executable location.",
  demoContract: "Load contract",
  demoContractDetail: "Read the generated public command definition.",
  demoUsage: "Render usage",
  demoUsageDetail: "Present the selected immutable command syntax.",
  demoOptions: "Render options",
  demoOptionsDetail: "Present only the compatible generated options and defaults.",
  endpointLocal: "Local",
  endpointRemote: "Remote",
  endpointWeb: "Web",
  endpointWebHook: "Web Hook",
  sourceLocalDescription: "Read from this device",
  destinationLocalDescription: "Write to this device",
  sourceRemoteDescription: "Read through a secure SSH connection",
  destinationRemoteDescription: "Write through a secure SSH connection",
  sourceWebDescription: "Open an upload page and send chosen files onward",
  destinationWebDescription: "Serve Source files through a download page",
  sourceWebHookDescription: "Receive files at a unique URL and deliver them onward",
  destinationWebHookDescription: "Send Source files to the destination URL",
} as const;

type Catalog = { readonly [Key in keyof typeof en]: string };

const ru = {
  brandProduct: "CLI доставки файлов",
  title: "Переносите файлы. Сохраняйте контроль.",
  tagline: "Надёжный CLI для локальных, SSH, браузерных и webhook-доставок.",
  install: "Установить Courier",
  installShort: "Установка",
  chooseChannel: "Выберите канал установки",
  copyCommand: "Скопировать команду",
  copiedCommand: "Скопировано",
  copyFailed: "Не удалось скопировать",
  packages: "Пакеты Linux",
  packagesDetail: "Пакеты Deb, RPM, APK и Arch для Ubuntu, Debian, Fedora, RHEL, Alpine, Arch Linux и Manjaro.",
  direct: "Готовые бинарники",
  directDetail: "Архивы релизов и checksums для macOS, Linux, Windows и поддерживаемых BSD helper-сборок.",
  routeShort: "Маршруты",
  routeTitle: "Выберите передачу",
  routeIntro: "Выберите Source, затем активируйте допустимый Destination.",
  sourceLabel: "Source",
  destinationLabel: "Destination",
  from: "from",
  to: "to",
  allowed: "Доступные параметры",
  cliShort: "CLI",
  cliTitle: "Команды и параметры",
  commandLabel: "Команда",
  optionsLabel: "Параметры",
  compatibleOnly: "Совместимые с выбранной командой",
  noCompatibleOptions: "У этой команды нет параметров.",
  product: "Основная",
  system: "Системная",
  optionDefault: "По умолчанию",
  applies: "Применяется к",
  repeatable: "Повторяемый",
  yes: "да",
  no: "нет",
  githubLabel: "Courier на GitHub",
  runDemo: "Запустить демо",
  replayDemo: "Повторить демо",
  preview: "Предпросмотр в браузере",
  noBrowserEffect: "Только предпросмотр. Браузер не запускает команду, установку или передачу.",
  routeDemoDescription: "Проверьте сгенерированную команду, смысл endpoints и безопасные этапы доставки.",
  installDemoDescription: "Посмотрите, как выбранный канал находит и проверяет релиз Courier.",
  cliDemoDescription: "Посмотрите сгенерированный usage и совместимые параметры выбранной команды.",
  selectCommand: "Выберите команду, чтобы открыть сгенерированную справку.",
  demoPreflight: "Preflight",
  demoPreflightDetail: "Проверка синтаксиса endpoints и безопасности Destination.",
  demoRoute: "Маршрут",
  demoRouteDetail: "Определение выбранных Source и Destination.",
  demoTransfer: "Передача",
  demoTransferDetail: "Предпросмотр bounded streaming с учётом подтверждённых байт.",
  demoVerify: "Проверка",
  demoVerifyDetail: "Подтверждение полученных данных до отчёта об успехе.",
  demoComplete: "Завершено",
  demoCompleteDetail: "Предпросмотр завершён. Данные не покидали страницу.",
  demoResolve: "Поиск релиза",
  demoResolveDetail: "Чтение метаданных последнего релиза из репозитория.",
  demoPlatform: "Выбор платформы",
  demoPlatformDetail: "Сопоставление операционной системы и архитектуры.",
  demoDownload: "Загрузка",
  demoDownloadDetail: "Предпросмотр получения подходящего автономного артефакта.",
  demoChecksum: "Проверка checksum",
  demoChecksumDetail: "Сравнение артефакта с опубликованной checksum.",
  demoInstall: "Установка",
  demoInstallDetail: "Предпросмотр размещения в управляемом каналом executable path.",
  demoContract: "Загрузка контракта",
  demoContractDetail: "Чтение сгенерированного определения публичной команды.",
  demoUsage: "Usage",
  demoUsageDetail: "Вывод неизменяемого синтаксиса выбранной команды.",
  demoOptions: "Параметры",
  demoOptionsDetail: "Вывод только совместимых сгенерированных параметров и defaults.",
  endpointLocal: "Local",
  endpointRemote: "Remote",
  endpointWeb: "Web",
  endpointWebHook: "Web Hook",
  sourceLocalDescription: "Читать с этого устройства",
  destinationLocalDescription: "Записать на это устройство",
  sourceRemoteDescription: "Читать через защищённое SSH-подключение",
  destinationRemoteDescription: "Записать через защищённое SSH-подключение",
  sourceWebDescription: "Открыть страницу загрузки и передать выбранные файлы дальше",
  destinationWebDescription: "Раздавать файлы Source через страницу скачивания",
  sourceWebHookDescription: "Принимать файлы по уникальной ссылке и доставлять дальше",
  destinationWebHookDescription: "Отправить файлы Source на destination URL",
} as const satisfies Catalog;

export const landingCatalogs = { en, ru } as const;
export type LandingMessage = keyof typeof en;

export function landingLocale(languages: readonly string[] = globalThis.navigator.languages): Locale {
  for (const language of languages) {
    const locale = parseLocale(language);
    if (locale) return locale;
  }
  return "en";
}

export function landingText(locale: Locale, message: LandingMessage): string {
  return landingCatalogs[locale][message];
}
