package contract

import (
	"bytes"
	"fmt"
	"go/format"
)

// HelpGo renders compact English metadata compiled into the Cobra binary.
func (c Contract) HelpGo() []byte {
	flags := make(map[string]Flag, len(c.Flags))
	for _, flag := range c.Flags {
		flags[flag.Name] = flag
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by contractdoc; DO NOT EDIT.\n\npackage app\n\n")
	output.WriteString("var generatedCommandHelp = map[string]structuredCommandHelp{\n")
	for _, command := range c.Commands {
		if command.Status != "shipped" && command.Status != "system" {
			continue
		}
		fmt.Fprintf(&output, "%q: {Usage: %q", command.Path, command.Usage)
		if len(command.Arguments) != 0 {
			output.WriteString(", Arguments: []structuredArgumentHelp{")
			for _, argument := range requiredArgumentsFirst(command.Arguments) {
				syntax := "<" + argument.Name + ">"
				if argument.Prefix != "" {
					syntax = argument.Prefix + " " + syntax
				}
				fmt.Fprintf(&output, "{Syntax: %q, Required: %t, Description: %q},", syntax, requiredValue(argument.Required), argument.Description.EN)
			}
			output.WriteString("}")
		}
		if len(command.Flags) != 0 {
			output.WriteString(", Flags: []structuredFlagHelp{")
			commandFlags := make([]Flag, 0, len(command.Flags))
			for _, name := range command.Flags {
				commandFlags = append(commandFlags, flags[name])
			}
			for _, flag := range requiredFlagsFirst(commandFlags) {
				fmt.Fprintf(&output, "{Name: %q, Syntax: %q, Required: %t, Description: %q, Default: %q, Repeatable: %t, AppliesTo: %q, Requires: %#v, Conflicts: %#v},", flag.Name, flag.Syntax, requiredValue(flag.Required), flag.Description.EN, flag.Default, flag.Repeatable, humanScopes(flag.AppliesTo, "en"), flag.Requires, flag.Conflicts)
			}
			output.WriteString("}")
		}
		output.WriteString("},\n")
	}
	output.WriteString("}\n")
	formatted, _ := format.Source(output.Bytes()) // generated tokens and quoted values always form valid Go
	return formatted
}
